services:
  kaggle:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    env_file:
      - .env
    volumes:
      - $PWD:/kaggle/working
      - $PWD/data:/kaggle/input
      - $PWD/.cache:/root/.cache
      - ~/.kaggle:/root/.kaggle
    working_dir: /kaggle/working
    ports:
      - 8889:8889
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8889 --no-browser --NotebookApp.token=''
    shm_size: '4gb'
    tty: true

